project: lbh-measure-python-service
version: 1.0-SNAPSHOT # Always keep the -SNAPSHOT unless you want overwrite the same image with each deployment
server:
  rootPath: /
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8000
kubernetes:
  cpus: 10
  mem: 10000
  workload: general
  healthcheck: default
  strategyType: Recreate
  env:
    prod:
      instances: 2
      cluster: sin0
      hpaSpec:
        maxReplicas: 3
        minReplicas: 2
        targetCPUUtilizationPercentage: 60
        targetMemoryUtilizationPercentage: 80
    dev:
      instances: 1
      cluster: cen0
      hpaSpec:
        maxReplicas: 2
        minReplicas: 1
        targetCPUUtilizationPercentage: 60
        targetMemoryUtilizationPercentage: 80
  containerSpec:
    volumeMounts:
      - name: ds-models-share
        mountPath: /models
    env:
      - name: CMS_DB_KEY
        valueFrom:
          secretKeyRef:
            name: ds-models-common
            key: lbh-measure-cms-db-key
      - name: CMS_DB_URI
        valueFrom:
          secretKeyRef:
            name: ds-models-common
            key: lbh-measure-cms-db-uri
      - name: STORAGE_CONN_STRING
        valueFrom:
          secretKeyRef:
            name: ds-models-common
            key: lbh-measure-storage-connection-string
  deploymentSpec:
    strategy:
      type: RollingUpdate
    template:
      spec:
        volumes:
          - name: ds-models-share
            azureFile:
              secretName: ds-models-common
              shareName: ds-models-share
              readOnly: false
